// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uscaefovbolfuvsbhcgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzY2FlZm92Ym9sZnV2c2JoY2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzQ3ODQsImV4cCI6MjA2MTExMDc4NH0.R-yktnICaH2d7JySNigPFTnbiztn4RXPOPhPGr69IBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);